### ISSUE TITLE
"Edit Me" links are broken

### ISSUE THREAD

**Issue by thisisshi** [capitalone/GoSwagless#1]
Steps to reproduce:
- Go to https://capitalone.github.io/GoSwagless/index.html
-  Link address for first Edit Me link is `https://github.com/capitalone/GoSwagless/blob/gh-pages//index.md`. The other ones on all pages are broken as well

**Comment by SanthiSridharan** [comment]
Thank you for opening the issue. We updated the config YML file to point to the correct basepath.
